name: Call a reusable workflow

on:
  push

jobs:
  call-workflow:
    uses: randomorg123/test2/.github/workflows/blank.yml@main
    
  blank:
    runs-on: ubuntu-latest
    steps:
      - name: MyCommands
        uses: randomorg123/test2@main
        
