name: Call a reusable workflow

on:
  push

jobs:
  call-workflow:
    uses: randomorg123/test2/.github/workflows/blank.yml@main
    
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: randomorg123/test2
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/my-private-repo
      - name: Run my action
        uses: ./.github/actions/my-private-repo/my-action
   
