name: blank
on:
  push:
jobs:
  blank:
    uses: randomorg123/test2/.github/workflows/blank.yml@main
  blank2:
    runs-on: ubuntu-latest
    steps:
      - name: MyCommands
        uses: randomorg123/test2@main

